<template>
  <div
    class="
      bg-white
      absolute
      inset-y-100
      bottom-9
      right-16
      sm:px-0
      z-10
      bg-white
    "
  >
    <div>
      <a
        href="#"
        aria-current="page"
        class="
          bg-white
          border-gray-300
          text-gray-500
          hover:bg-gray-50
          relative
          items-center
          px-4
          py-2
          border
          text-sm
          font-medium
          hover:border-red-500
          focus:border-red-500
          focus:text-red-500
        "
        @click="handleClick"
      >
        1
      </a>
      <a
        href="#"
        class="
          bg-white
          border-gray-300
          text-gray-500
          hover:bg-gray-50
          relative
          items-center
          px-4
          py-2
          border
          text-sm
          font-medium
          hover:border-red-500
          focus:border-red-500
          focus:text-red-500
        "
        @click="handleClickTwo"
      >
        2
      </a>
      <a
        href="#"
        class="
          bg-white
          border-gray-300
          text-gray-500
          hover:bg-gray-50
          relative
          items-center
          px-4
          py-2
          border
          text-sm
          font-medium
          hover:border-red-500
          focus:border-red-500
          focus:text-red-500
        "
        @click="handleClickThree"
      >
        3
      </a>
      <a
        href="#"
        class="
          relative
          items-center
          px-2
          py-2
          rounded-r-md
          border border-gray-300
          bg-white
          text-sm
          font-medium
          text-gray-500
          hover:border-red-500
          focus:border-red-500
          focus:text-red-500
        "
      >
        <span class="sr">>></span>
      </a>
    </div>
  </div>
</template>

<script>
export default {
  name: 'Pages',
  methods: {
    handleClick() {
      this.$emit('handleClick')
    },
    handleClickTwo() {
      this.$emit('handleClickTwo')
    },

    handleClickThree() {
      this.$emit('handleClickThree')
    },
  },
}
</script>
